<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">

<CURRICULO>
	<ID><xsl:value-of select="CURRICULO-VITAE/@NUMERO-IDENTIFICADOR"/></ID>
	<NOME><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/@NOME-COMPLETO"/></NOME>
	<OUTRAS-ORIENTACOES-EM-ANDAMENTO>
		<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA">
			<OUTRA-ORIENTACAO-EM-ANDAMENTO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@TITULO-DO-TRABALHO"/></TITULO>
				<DOI><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@ANO"/></ANO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@NOME-CURSO"/></NOME-CURSO>
			</OUTRA-ORIENTACAO-EM-ANDAMENTO>
    	</xsl:for-each>
	</OUTRAS-ORIENTACOES-EM-ANDAMENTO>
</CURRICULO>
  
</xsl:template>
</xsl:stylesheet>
