<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">

<CURRICULO>
	<ID><xsl:value-of select="CURRICULO-VITAE/@NUMERO-IDENTIFICADOR"/></ID>
	<NOME><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/@NOME-COMPLETO"/></NOME>
	<ORIENTACOES-EM-ANDAMENTO-DE-MESTRADO>
		<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO">
			<ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@TITULO-DO-TRABALHO"/></TITULO>
				<DOI><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@ANO"/></ANO>
				<NUMERO-ID-ORIENTADO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NUMERO-ID-ORIENTADO"/></NUMERO-ID-ORIENTADO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-CURSO"/></NOME-CURSO>
			</ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO>
    	</xsl:for-each>
	</ORIENTACOES-EM-ANDAMENTO-DE-MESTRADO>
</CURRICULO>
  
</xsl:template>
</xsl:stylesheet>
