<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">

<CURRICULO>
	<ID><xsl:value-of select="CURRICULO-VITAE/@NUMERO-IDENTIFICADOR"/></ID>
	<NOME><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/@NOME-COMPLETO"/></NOME>
	<ORIENTACOES-CONCLUIDAS>
		
		<xsl:for-each select="CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-MESTRADO">
			<ORIENTACAO>
				<TIPO>
					MESTRADO
				</TIPO>

				<TITULO>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@TITULO"/>
				</TITULO>

				<ANO>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@ANO"/>
				</ANO>

				<NATUREZA>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NATUREZA"/>
				</NATUREZA>

				<IDIOMA>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@IDIOMA"/>
				</IDIOMA>

				<PAIS>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@PAIS"/>
				</PAIS>

				<ORIENTADO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DO-ORIENTADO"/>
				</ORIENTADO>

				<CURSO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DO-CURSO"/>
				</CURSO>

				<INSTITUICAO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DA-INSTITUICAO"/>
				</INSTITUICAO>

				<AGENCIA>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO/@NOME-DA-AGENCIA"/>
				</AGENCIA>

			</ORIENTACAO>
		</xsl:for-each>


		<xsl:for-each select="CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO">
			<ORIENTACAO>
				<TIPO>
					DOUTORADO
				</TIPO>

				<TITULO>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@TITULO"/>
				</TITULO>

				<ANO>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@ANO"/>
				</ANO>

				<NATUREZA>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@NATUREZA"/>
				</NATUREZA>

				<IDIOMA>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@IDIOMA"/>
				</IDIOMA>

				<PAIS>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@PAIS"/>
				</PAIS>

				<ORIENTADO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@NOME-DO-ORIENTADO"/>
				</ORIENTADO>

				<CURSO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@NOME-DO-CURSO"/>
				</CURSO>

				<INSTITUICAO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@NOME-DA-INSTITUICAO"/>
				</INSTITUICAO>

				<AGENCIA>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO/@NOME-DA-AGENCIA"/>
				</AGENCIA>

			</ORIENTACAO>
		</xsl:for-each>

		<xsl:for-each select="CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO">
			<ORIENTACAO>
				<TIPO>
					POS-DOUTORADO
				</TIPO>

				<TITULO>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@TITULO"/>
				</TITULO>

				<ANO>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@ANO"/>
				</ANO>

				<NATUREZA>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@NATUREZA"/>
				</NATUREZA>

				<IDIOMA>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@IDIOMA"/>
				</IDIOMA>

				<PAIS>
					<xsl:value-of select="DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@PAIS"/>
				</PAIS>

				<ORIENTADO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@NOME-DO-ORIENTADO"/>
				</ORIENTADO>

				<CURSO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@NOME-DO-CURSO"/>
				</CURSO>

				<INSTITUICAO>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@NOME-DA-INSTITUICAO"/>
				</INSTITUICAO>

				<AGENCIA>
					<xsl:value-of select="DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-POS-DOUTORADO/@NOME-DA-AGENCIA"/>
				</AGENCIA>
			</ORIENTACAO>
		</xsl:for-each>

		<xsl:for-each select="CURRICULO-VITAE/OUTRA-PRODUCAO/ORIENTACOES-CONCLUIDAS/OUTRAS-ORIENTACOES-CONCLUIDAS">
			<ORIENTACAO>
				<TIPO>
					OUTRAS
				</TIPO>

				<TITULO>
					<xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@TITULO"/>
				</TITULO>

				<ANO>
					<xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@ANO"/>
				</ANO>

				<NATUREZA>
					<xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NATUREZA"/>
				</NATUREZA>

				<IDIOMA>
					<xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@IDIOMA"/>
				</IDIOMA>

				<PAIS>
					<xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@PAIS"/>
				</PAIS>

				<ORIENTADO>
					<xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DO-ORIENTADO"/>
				</ORIENTADO>

				<CURSO>
					<xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DO-CURSO"/>
				</CURSO>

				<INSTITUICAO>
					<xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DA-INSTITUICAO"/>
				</INSTITUICAO>

				<AGENCIA>
					<xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS/@NOME-DA-AGENCIA"/>
				</AGENCIA>

			</ORIENTACAO>
		</xsl:for-each>
    	
	</ORIENTACOES-CONCLUIDAS>
</CURRICULO>
  
</xsl:template>
</xsl:stylesheet>
