<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">

<CURRICULO>
	<ID><xsl:value-of select="CURRICULO-VITAE/@NUMERO-IDENTIFICADOR"/></ID>
	<NOME><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/@NOME-COMPLETO"/></NOME>
	<GRADUACAO>		
		<CODIGO-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/GRADUACAO/@CODIGO-INSTITUICAO"/></CODIGO-INSTITUICAO>
		<NOME-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/GRADUACAO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
		<TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/GRADUACAO/@TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO"/></TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO>
		<NOME-CURSO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/GRADUACAO/@NOME-CURSO"/></NOME-CURSO>	
	</GRADUACAO>
	<MESTRADO>		
		<CODIGO-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/MESTRADO/@CODIGO-INSTITUICAO"/></CODIGO-INSTITUICAO>
		<NOME-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/MESTRADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
		<TITULO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/MESTRADO/@TTITULO-DA-DISSERTACAO-TESE"/></TITULO>
		<NOME-CURSO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/MESTRADO/@NOME-CURSO"/></NOME-CURSO>	
	</MESTRADO>
	<DOUTORADO>		
		<CODIGO-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/DOUTORADO/@CODIGO-INSTITUICAO"/></CODIGO-INSTITUICAO>
		<NOME-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/DOUTORADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
		<TITULO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/DOUTORADO/@TITULO-DA-DISSERTACAO-TESE"/></TITULO>
		<NOME-CURSO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/DOUTORADO/@NOME-CURSO"/></NOME-CURSO>	
	</DOUTORADO>
	<POS-DOUTORADO>		
		<CODIGO-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/POS-DOUTORADO/@CODIGO-INSTITUICAO"/></CODIGO-INSTITUICAO>
		<NOME-INSTITUICAO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/POS-DOUTORADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
		<TITULO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/POS-DOUTORADO/@TITULO-DO-TRABALHO"/></TITULO>
		<NOME-CURSO><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/FORMACAO-ACADEMICA-TITULACAO/POS-DOUTORADO/@NOME-CURSO"/></NOME-CURSO>	
	</POS-DOUTORADO>
	
	
	
	
</CURRICULO>
  
</xsl:template>
</xsl:stylesheet>
