<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">

<CURRICULO>
	<ID><xsl:value-of select="CURRICULO-VITAE/@NUMERO-IDENTIFICADOR"/></ID>
	<NOME><xsl:value-of select="CURRICULO-VITAE/DADOS-GERAIS/@NOME-COMPLETO"/></NOME>
	<ORIENTACOES-CONCLUIDAS>
		<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO">
			<ORIENTACAO>
				<TIPO>
					DOUTORADO
				</TIPO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@TITULO-DO-TRABALHO"/></TITULO>
				<DOI><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@ANO"/></ANO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO/@NOME-CURSO"/></NOME-CURSO>
			</ORIENTACAO>
    	</xsl:for-each>
		<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA">
			<ORIENTACAO>
				<TIPO>
					INICIACAO-CIENTIFICA
				</TIPO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@TITULO-DO-TRABALHO"/></TITULO>
				<DOI><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@ANO"/></ANO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA/@NOME-CURSO"/></NOME-CURSO>
			</ORIENTACAO>
    	</xsl:for-each>
		<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO">
			<ORIENTACAO>
				<TIPO>
					MESTRADO
				</TIPO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@TITULO-DO-TRABALHO"/></TITULO>
				<DOI><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@ANO"/></ANO>
				<NUMERO-ID-ORIENTADO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NUMERO-ID-ORIENTADO"/></NUMERO-ID-ORIENTADO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO/@NOME-CURSO"/></NOME-CURSO>
			</ORIENTACAO>
    	</xsl:for-each>
    	
    	<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/OUTRAS-ORIENTACOES-EM-ANDAMENTO">
			<ORIENTACAO>
				<TIPO>
					OUTRAS
				</TIPO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@TITULO-DO-TRABALHO"/></TITULO>
		  		<DOI><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@ANO"/></ANO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DE-OUTRAS-ORIENTACOES-EM-ANDAMENTO/@NOME-CURSO"/></NOME-CURSO>
			</ORIENTACAO>
    	</xsl:for-each>
		<xsl:for-each select="CURRICULO-VITAE/DADOS-COMPLEMENTARES/ORIENTACOES-EM-ANDAMENTO/ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO">
			<ORIENTACAO>
				<TIPO>
					POS-DOUTORADO
				</TIPO>
		  		<TITULO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@TITULO-DO-TRABALHO"/></TITULO>
				<DOI><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@DOI"/></DOI>
				<IDIOMA><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@IDIOMA"/></IDIOMA>
				<ANO><xsl:value-of select="DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@ANO"/></ANO>
				<NOME-DO-ORIENTANDO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@NOME-DO-ORIENTANDO"/></NOME-DO-ORIENTANDO>
				<NOME-INSTITUICAO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@NOME-INSTITUICAO"/></NOME-INSTITUICAO>
				<NOME-CURSO><xsl:value-of select="DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO/@NOME-CURSO"/></NOME-CURSO>
			</ORIENTACAO>
    	</xsl:for-each>
    </ORIENTACOES-CONCLUIDAS>
</CURRICULO>
  
</xsl:template>
</xsl:stylesheet>

